version: '3'

services:
  osrm:
    build: './apps/osrm'
    ports:
      - 5000:5000

  db:
    image: 'postgis/postgis:14-3.3-alpine'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
